### ISSUE TITLE
MojoDatabase 问题

### ISSUE THREAD

**Issue by tyrone782** [zhuchaowe/EasyIOS#12]
MojoDatabase这个开源项目早就已经停止维护，使用中发现对表关联的处理没有实现。希望能得到增强。

另外Easy使用其配合JSONModel，对基本数据类型（如NSInteger, CGFloat，BOOL等）支持力度还不够，希望得到改善。

**Comment by zhuchaowe** [comment]
MojoDatabase 是被我大量修改过的https://github.com/EasyIOS/mojo-database，目前关联表功能确实是缺失的，不过建议你迁移到swift版本的https://github.com/EasyIOS/EasyCoreData

**Comment by tyrone782** [comment]
swift版本有什么新的特性么？
是不是打算以后ObjectiveC版本的不继续维护了？

**Comment by zhuchaowe** [comment]
swift版本特性可以看
https://github.com/EasyIOS/EasyIOS-Swift 
ObjectiveC版本还会继续维护，保证稳定的，但是新特性可能暂时不会再加了。
不过因为开源了，维护者不一定是我一个人，大家都可以提交代码，增加新特性
